version: '2'
services:
    bahstaffingportal-app:
        image: bahstaffingportal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bahstaffingportal-mysql:3306/bahstaffingportal?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=bahstaffingportal-elasticsearch:9300
        ports:
            - 8080:8080
    bahstaffingportal-mysql:
        extends:
            file: mysql.yml
            service: bahstaffingportal-mysql
    bahstaffingportal-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: bahstaffingportal-elasticsearch
