version: '2'
services:
    univportal-app:
        image: univportal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://univportal-mysql:3306/univportal?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    univportal-mysql:
        extends:
            file: mysql.yml
            service: univportal-mysql
